In [17]:
import numpy as np

class AdalineGD2(object):
    def __init__(self, eta = 0.01, n_iter = 50, random_state = 1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        
    def fit (self, X, y):
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc = 0.0, scale = 0.01, size = 1 + X_train.shape[1])
        self.cost_ = []
        
        for i in range(self.n_iter):
            cost = 0
            for xi, target in zip(X, y):
                net_input = self.net_input(xi)
                output = self.activation(net_input)
                errors = (target - output)
                for z in range(len(xi)):
                    self.w_[1+z] += self.eta * errors * xi[z]
                self.w_[0] += self.eta * errors
                cost += (errors ** 2) / 2.0
            self.cost_.append(errors)
            print(f"cost = {cost} and iteration = {i}")
        return self

    def net_input (self, X):
        sum_ = 0
        for xi in range(len(X)):
            sum_ += X[xi] * self.w_[1 + xi]
        sum_ += self.w_[0]
        return sum_
    
    def activation (self, X):
        return X
    
    def predict (self, X):
        if self.activation(self.net_input(X)) >= 0.0:
            return 1
        else:
            return -1

In [2]:
#Scikit learn
from sklearn import datasets

In [3]:
iris2 = datasets.load_iris()

In [9]:
iris2;

In [7]:
X = iris2.data[:100, [0, 2]]

In [8]:
X;

In [23]:
y = iris2.target[:100]

In [24]:
np.unique(y)

array([0, 1])

In [25]:
np.unique(iris2.target)

array([0, 1, 2])

In [26]:
y = np.where (y == 0, -1, 1)

In [27]:
np.unique(y)

array([-1,  1])

In [65]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1, stratify = y)

In [66]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [67]:
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [68]:
X_train_std

array([[ 0.36500087,  0.90871364],
       [-0.73986663, -1.0134002 ],
       [-1.84473414, -1.21934097],
       [-0.73986663, -0.87610635],
       [ 1.15419195,  1.11465441],
       [ 0.36500087,  1.11465441],
       [ 0.52283909, -1.15069404],
       [-0.58202842, -0.94475328],
       [-0.58202842, -0.87610635],
       [ 1.31203016,  1.3892421 ],
       [-0.58202842, -0.94475328],
       [-1.21338128, -1.08204712],
       [-0.10851377,  1.11465441],
       [ 1.46986838,  1.11465441],
       [-1.68689592, -1.08204712],
       [-0.10851377, -0.94475328],
       [ 0.04932444, -1.0134002 ],
       [ 0.04932444,  0.7714198 ],
       [-0.4241902 , -0.94475328],
       [ 0.04932444,  1.04600749],
       [-0.10851377, -0.94475328],
       [ 0.04932444,  0.56547903],
       [-1.37121949, -1.0134002 ],
       [-0.58202842, -0.67016558],
       [ 0.83851552,  1.52653595],
       [-0.73986663,  0.29089134],
       [ 0.99635373,  1.18330133],
       [-0.73986663, -1.0134002 ],
       [-0.73986663,

In [69]:
ad3 = AdalineGD2 (eta = 0.01, n_iter = 20)
ad3.fit(X_train_std, y_train)

cost = 18.023576190592664 and iteration = 0
cost = 6.1453449686445545 and iteration = 1
cost = 4.566330387479942 and iteration = 2
cost = 3.808798091103492 and iteration = 3
cost = 3.2763904512630333 and iteration = 4
cost = 2.8847780947055135 and iteration = 5
cost = 2.59507737282306 and iteration = 6
cost = 2.380630276809848 and iteration = 7
cost = 2.2219404406693997 and iteration = 8
cost = 2.1045825416236297 and iteration = 9
cost = 2.017857930438051 and iteration = 10
cost = 1.9538288403128297 and iteration = 11
cost = 1.9066064888754517 and iteration = 12
cost = 1.8718231823359381 and iteration = 13
cost = 1.8462403562144833 and iteration = 14
cost = 1.8274574912406811 and iteration = 15
cost = 1.8136959542337365 and iteration = 16
cost = 1.8036384952553073 and iteration = 17
cost = 1.796310085317536 and iteration = 18
cost = 1.7909894586189516 and iteration = 19


In [70]:
for i in range(20):
    if (y_test[i] != ad3.predict(X_test_std[i])):
        print("Error!")
    else:
        print("Correct")

Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct


In [71]:
ad3.w_

array([-0.00218676, -0.12837228,  1.07336792])

In [72]:
import numpy as np

class LogisticRegression(object):
    def __init__(self, eta = 0.01, n_iter = 50, random_state = 1):
        self.eta = eta
        self.n_iter = n_iter
        self.random_state = random_state
        
    def fit (self, X, y):
        rgen = np.random.RandomState(self.random_state)
        self.w_ = rgen.normal(loc = 0.0, scale = 0.01, size = 1 + X_train.shape[1])
        self.cost_ = []
        
        for i in range(self.n_iter): # n_iter number of training epochs
            cost = 0
            for xi, target in zip(X, y):
                net_input = self.net_input(xi)
                output = self.activation(net_input)
                errors = (target - output)
                for z in range(len(xi)):
                    self.w_[1+z] += self.eta * errors * xi[z]
                self.w_[0] += self.eta * errors
                cost += -target * np.log(output) - (1 - target) * np.log(1 - output) # changed
            self.cost_.append(errors)
            print(f"cost = {cost} and iteration = {i}")
        return self

    def net_input (self, X):
        sum_ = 0
        for xi in range(len(X)):
            sum_ += X[xi] * self.w_[1 + xi]
        sum_ += self.w_[0]
        return sum_
    
    def activation (self, z):
        return 1. / (1. + np.exp(-z)) # changed
    
    def predict (self, X):
        if self.net_input(X) >= 0.0: # changed
            return 1
        else:
            return 0

In [74]:
y_train

array([ 1, -1, -1, -1,  1,  1, -1, -1, -1,  1, -1, -1,  1,  1, -1, -1, -1,
        1, -1,  1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1,  1,  1, -1, -1,
        1,  1,  1, -1,  1,  1,  1, -1, -1,  1,  1,  1, -1, -1,  1,  1,  1,
       -1, -1, -1,  1, -1,  1, -1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1,
       -1, -1, -1,  1,  1, -1, -1, -1,  1,  1, -1,  1])

In [75]:
y_train = np.where (y_train == -1, 0, 1)
y_train

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])

In [80]:
y_test = np.where (y_test == -1, 0, 1)
len(y_test)

20

In [77]:
lrgd = LogisticRegression(eta = 0.05, n_iter = 1000, random_state = 1)

In [78]:
lrgd.fit(X_train_std, y_train)

cost = 29.568444116347095 and iteration = 0
cost = 13.613422350316005 and iteration = 1
cost = 9.427797736653222 and iteration = 2
cost = 7.386736093267943 and iteration = 3
cost = 6.146152699557998 and iteration = 4
cost = 5.299678826116442 and iteration = 5
cost = 4.679191114521461 and iteration = 6
cost = 4.201592523408109 and iteration = 7
cost = 3.820731309825926 and iteration = 8
cost = 3.5087574900702263 and iteration = 9
cost = 3.247785294812986 and iteration = 10
cost = 3.025756735408316 and iteration = 11
cost = 2.8342199153479464 and iteration = 12
cost = 2.6670583237137295 and iteration = 13
cost = 2.519725908724477 and iteration = 14
cost = 2.3887666332925854 and iteration = 15
cost = 2.2715016879613286 and iteration = 16
cost = 2.1658195013177024 and iteration = 17
cost = 2.070030960891316 and iteration = 18
cost = 1.9827672424245282 and iteration = 19
cost = 1.9029062112986888 and iteration = 20
cost = 1.8295184288602193 and iteration = 21
cost = 1.76182688892248 and ite

cost = 0.0687130179904241 and iteration = 809
cost = 0.06863412006105486 and iteration = 810
cost = 0.06855540975106021 and iteration = 811
cost = 0.06847688638417405 and iteration = 812
cost = 0.06839854928740086 and iteration = 813
cost = 0.06832039779098975 and iteration = 814
cost = 0.06824243122841388 and iteration = 815
cost = 0.06816464893634584 and iteration = 816
cost = 0.06808705025465467 and iteration = 817
cost = 0.06800963452636791 and iteration = 818
cost = 0.0679324010976666 and iteration = 819
cost = 0.06785534931785524 and iteration = 820
cost = 0.06777847853935409 and iteration = 821
cost = 0.06770178811767287 and iteration = 822
cost = 0.06762527741139188 and iteration = 823
cost = 0.06754894578214987 and iteration = 824
cost = 0.06747279259462163 and iteration = 825
cost = 0.06739681721649735 and iteration = 826
cost = 0.06732101901847197 and iteration = 827
cost = 0.06724539737421945 and iteration = 828
cost = 0.06716995166038055 and iteration = 829
cost = 0.067094

In [79]:
for i in range(len(y_test)):
    if (y_test[i] != lrgd.predict(X_test_std[i])):
        print("Error!")
    else:
        print("Correct")

Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct
Correct


In [83]:
from sklearn.linear_model import Perceptron
ppn = Perceptron(eta0 = 0.1, max_iter = 10, random_state = 1)
ppn.fit(X_train_std, y_train)
y_pred = ppn.predict(X_test_std)
print("Misclassified examples: %d" % (y_test != y_pred).sum())

Misclassified examples: 10


In [85]:
X = iris2.data[:, 0:2]
y = iris2.target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1, stratify = y)

In [86]:
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

In [87]:
ppn.fit(X_train_std, y_train)
y_pred = ppn.predict(X_test_std)
print("Misclassified examples: %d" % (y_test != y_pred).sum())

Misclassified examples: 8
